### PR TITLE
UploadControl: Added setAllowedType

### PR DESCRIPTION
**Pull request by JanGalek**
- bug fix? no 
- new feature? yes
- BC break? no
- doc PR: nette/docs#???  - if it will merged I will send PR

Added new method to UploadControl, whitch set mimeTypes and attribute accept.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Related https://github.com/nette/forms/commit/b48d57d6e75fabfe6b3b09c4268a02cc95859618#diff-31d0814231016345eaa29e9607fc0c15

**Comment by JanGalek** [comment]
@JanTvrdik ou, ok I will remove js, and rebase. 

Firefox 👎

**Comment by JanGalek** [comment]
@JanTvrdik https://bugzilla.mozilla.org/show_bug.cgi?id=373621, fixed ? 

I try js log and firefox (57.0) return same type as chrome

**Comment by JanTvrdik** [comment]
@JanGalek The commit is from 2014 and the issue is resolved. But it's still sth that need's to be considered.

**Comment by JanGalek** [comment]
@JanTvrdik ok, and if we Dtect firefox <= 50 and type needed is application/pdf than we allow application/x-download with check extension ?

Problem was with PDF right ?

**Comment by dg** [comment]
What about to add attribute `accept`, when rule MIME_TYPE is used? The same way as i.e. attribute range is added in TextInput::addRule().

**Pull request closed without merging**
