### PR TITLE
Fix JS range validator

### PR DESCRIPTION
**Pull request by jannavratil**
Allow use comma in numbers as decimal point. 
Remove unnecessary argument in toggle method

### CODE REVIEW

**Comment by dg** [comment]
Example of usage?

Argument in toggle method is intentional.

**Comment by jannavratil** [comment]
Change allow users to insert number with comma as decimal point in range from. One number from range compared is parsed to fload but another not.

Bad situation without chynges:

http://jsfiddle.net/kurnick/6p5a65ek/1/

And here fixed situation:

http://jsfiddle.net/kurnick/x5oded3q/3/


And that intentional argument looks weird to me. Could you explain why it is intentional?

**Comment by jannavratil** [comment]
ping @dg

**Comment by dg** [comment]
It is not so easy to fix properly.

**Pull request closed without merging**
