### PR TITLE
Controls: element prototypes

### PR DESCRIPTION
**Pull request by matej21**
CheckBoxList item label prototype:
- BC break: attributes of main label are ignored for individual item labels
- fixes consistency - radiolist already has itemLabelPrototype
- http://forum.nette.org/cs/22457-checkboxlist-a-pridani-atributu-jako-je-treba-class-nebo-data-atribut-k-jednotlivym-checkboxum-v-listu (see my comment there)

SelectBox and MultiselectBox item prototype
- BC break: no
- simplifies http://forum.nette.org/cs/22874-select-a-options-data-attributy

### CODE REVIEW

**Comment by dg** [comment]
I'm not sure whether it is good idea to store SelectBox item prototype as Html object. Only attributes are used, more precisely, it is not HTML attributes, it is special attributes like `data-foo:` (with colon).

**Comment by matej21** [comment]
I know it is not ideal. But Utils\Html api is well known and I didn't want to introduce a new api. 
But I'm open to your suggestions. Maybe just use an array and `setItemAttributes` (or `addItemAttributes`)?

**Comment by dg** [comment]
Maybe `setItemLabelAttributes`? Yes, it is long, but it will be used rarely.

Probably for consistency the same method should be added to RadioList.

**Comment by matej21** [comment]
I thought we were talking about selectbox items, not about checkboxlist (and radiolist) labels.

**Comment by dg** [comment]
`SelectBox::setItemAttribute` and `CheckboxList::setItemLabelAttribute`

**Comment by matej21** [comment]
I've updated SelectBox and MultiSelectBox, but I think CheckboxList should have getItemLabelPrototype since the label is fully featured html element (it could have class, style...).

**Comment by dg** [comment]
- CheckboxList::$itemLabelPrototype is OK, it is consistent with RadioList.
- MultiSelectBox::setItemAttributes() is not actually `set`, but `add`. I don't know if is better set or add, but name must correspond with its functionality. 
- what about 'option' instead of 'item'? Will be 'item' attributes used for optgroups?

**Comment by dg** [comment]
CheckboxList::$itemLabelPrototype is already added here #92

**Comment by matej21** [comment]
Updated, failing tests are related to the https://github.com/nette/latte/commit/b3b6a1dd650dced1ccf8f34941930f1049ada584

**Comment by matej21** [comment]
rebased

**Comment by dg** [comment]
Merged e9849efae148878c304c78a82772781c24293fc6

**Comment by matej21** [comment]
thanks!

**Pull request closed without merging**
