### PR TITLE
Update addError to use method getTranslator

### PR DESCRIPTION
**Pull request by thorewi**
instead of accessing property directly.

- bug fix
- BC break? no
- doc PR: no

### CODE REVIEW

**Comment by JanTvrdik** [comment]
why?

**Comment by thorewi** [comment]
Because when I override getTranslator method, the method is not used.

**Comment by dg** [comment]
This is a very non-standard approach and it would not be possible to rely on it in the future.

**Comment by thorewi** [comment]
Why is it very non-standard? I want the translator to be lazy...

**Comment by dg** [comment]
So create proxy translator that creates lazy translator. https://en.wikipedia.org/wiki/Proxy_pattern

**Comment by thorewi** [comment]
Yes, normally I use https://github.com/Ocramius/ProxyManager but sometimes you can't proxy some 3rd party libraries (for example because of own implementation of __isset method) and you don't want to write proxy on your own... So what's wrong on this approach (to use getTranslator method anywhere)?

**Comment by dg** [comment]
I am talking about proxy for Translator:

```php

class Translator implements Nette\Locationzation\Translator
{
	function translate($x)
	{
		return $this->getTranslator()->translate($x);
	}

	private function getTranslator()
	{
		$translator = getItSomehowLazy();
		return $tranlator;
	}
}

**Pull request closed without merging**
