### PR TITLE
Rename Html:add() to Html:addHtml() to follow nette/utils#111

### PR DESCRIPTION
**Pull request by spaze**
nette/utils#111 has renamed `Html::add()` to `Html::addHtml()`, this is a followup pull request to use the new name in nette/forms

### CODE REVIEW

**Comment by hrach** [comment]
You will need to add proper constraits to composer.

**Comment by spaze** [comment]
Indeed, thanks @hrach. Dependencies need to be updated but I don't know how to do it before nette/utils#111 is merged in. Any idea?

**Comment by enumag** [comment]
If we assume that https://github.com/nette/utils/pull/111 will be merged into Nette 2.4 before the first stable is released then there is no need to change composer.json - nette/forms already depends on nette/utils 2.4.

**Comment by spaze** [comment]
Thanks, @dg!

**Comment by dg** [comment]
Thank you :)

**Pull request merged**
