### PR TITLE
Labels with Nette\Utils\Html are not translated

### PR DESCRIPTION
**Pull request by MilanPala**
- bug fix: yes
- BC break? no

### CODE REVIEW

**Comment by dg** [comment]
Which bug does it solve?

**Comment by mabar** [comment]
Translator which supports only strings, I guess.

Easier would be solve it in translator, this is probably not the only place where is non-string value translated.

```php
if (!is_string($message)) {
  return (string) $message;
}
```

**Comment by dg** [comment]
It creates inconsistency with others usage of translate().

**Comment by MilanPala** [comment]
With behavior in Nette 3 i can't use `Nette\Utils\Html` as label (for example with links to terms and conditions). In Nette 2 I create label with link and push it into `Nette\Forms\Controls\Checkbox`. It works in Nette 3 too: https://github.com/nette/forms/blob/master/src/Forms/Controls/Checkbox.php#L26 But translator converts \Nette\Utils\Html\ instance into `string` and escape html tags into entities: https://github.com/nette/forms/blob/master/src/Forms/Controls/BaseControl.php#L279 and https://github.com/nette/utils/blob/master/src/Utils/ITranslator.php#L22

In Nette 2 I don't change `Nette\Utils\Html` in my translator and it works so far:

```
	if ($message instanceof Nette\Utils\Html) {
			return $message;
	}
```

-------------------

In this case would be better use `Nette\Forms\Controls\BaseControl::translate` instead of `$this->getForm()->getTranslator()->translate()` in https://github.com/nette/forms/blob/master/src/Forms/Controls/BaseControl.php#L278-L279, because this method has condition for this use case. What do you think?

**Comment by mabar** [comment]
I see. Translator must return string, which is escaped by template engine.

**Comment by dg** [comment]
Thanks

**Pull request merged**
