### PR TITLE
Fixed <label n:name /> checkbox label rendering

### PR DESCRIPTION
**Pull request by Koricz**
- bugfix
- issues - #83
- documentation - not needed
- BC break - no

### CODE REVIEW

**Comment by Koricz** [comment]
@dg Failing test for current revision https://github.com/Koricz/forms/commit/ffcb8aed67f1ebf3fe6bc4033505bd4635544f84

**Comment by dg** [comment]
It will probably not work with addRadioList

**Comment by Koricz** [comment]
Yes, you are right. This fix is for simple checkbox only and not working with RadioLists and CheckboxLists. There is partial rendering for them.

As I wrote in https://github.com/nette/forms/issues/83 now you can use

`{label checkbox: /} {input checkbox:} ` or
`<label n:name="checkbox" /> <input n:name="checkbox">` which wasn't possible.

**Comment by dg** [comment]
I think that `<label n:name=radiolist />` will behave incorrectly now.

**Comment by Koricz** [comment]
Ok, now I know what you mean. There is no test for this and I never use it for RadioList or CheckboxList ;-) I will try to find solution...

**Comment by Koricz** [comment]
So, I played with almost all possible combinations and the checkbox / RadioList is the problematic part.

In mine new proposal https://github.com/Koricz/forms/commit/b0dd9a17fb8291d1e56952425db03241948181e0  there is BC break with checkbox input rendering and partial rendering now supports multi options control values.

In current state you can use `<input n:name="checkbox">`, checkbox input name must include colon (`:`)  in mine.

`$form->addRadioList('radiolist', 'Radio list label', array(0 => 'A', '1' => 'B'));`
`$form->addCheckbox('checkbox', 'Checkbox label');`
`$form->addCheckboxList('checkboxlist', 'CheckboxList label', array(0 => 'A', 1 => 'B'));`

Current revision

`<label n:name="radiolist" /> //error`
`<label n:name="checkbox:" /> //error`
`<label n:name="checkbox" /> //error`
`<label n:name="checkboxlist" /> //error`

`<input n:name="checkbox"> //input`
`<input n:name="checkbox:"> //input`

Partial rendering

`<label n:name="radiolist:0" /> //Radio list label`
`<label n:name="checkboxlist:0 /> //CheckboxList label`


My propoposal

`<label n:name="radiolist" /> //Radio list label`
`<label n:name="checkbox:" /> //Checkbox label`
`<label n:name="checkbox" /> //error`
`<label n:name="checkboxlist" /> //CheckboxList label`

`<input n:name="checkbox"> //error`
`<input n:name="checkbox:"> //input`

Updated partial rendering

`<label n:name="radiolist:0" /> //A`
`<label n:name="checkboxlist:0 /> //A`

Partial rendering is now more practical, I can write templates even without programming
```javascript
<tr>
	<td><label n:name="radiolist" /></td>
</tr>
<tr>
  <td>
     <label n:name="radiolist:0" /><input n:name="radiolist:0">
     <label n:name="radiolist:1" /><input n:name="radiolist:1">
  </td>
</tr>
```

And there is a common syntax now for 

`{label checkbox: /} {input checkbox: }` and
`<label n:name="checkbox:" /> <input n:name="checkbox:">`  

Is anyone interested for this change? 

If yes, I will write some additional tests and create regular PR, otherwise, at least, I had some practice with macros :-)

**Comment by dg** [comment]
Merged c2805efb1f7561e576df08f1ea3dceb800a00483, thank you.

**Pull request closed without merging**
