### PR TITLE
ControlGroup: allows Container inside ControlGroup

### PR DESCRIPTION
**Pull request by castamir**
In current state, `$form->addComponent($container, 'name')` won't be added into any group.

This pull request adds support for such containers (including nested containers).

### CODE REVIEW

**Comment by dg** [comment]
I think that better test is to use `$form->getGroups()` and `$group->getControls()` than rendering.

**Comment by castamir** [comment]
I'll create another test for groups behaviour, but the current test should stay too.

**Comment by castamir** [comment]
Is it OK, now? Should I squash these commits?

**Comment by dg** [comment]
Will it work with this?

```php
$container = $form->addContainer('cont');
$container->addText('name');
```

**Comment by castamir** [comment]
This should be compatible with `addComponent()`, otherwise it would be confusing.

I'll look at it tomorrow

**Comment by castamir** [comment]
It should be OK now.

**Comment by dg** [comment]
This seems ok. But it is BC break, so it should be targeted to master, not to 2.3.

The rendering test is really inappropriate. This type of tests are historical relics that should be rewritten. It makes my work harder, because I must update test when rendering of some elements somehow differs etc.

**Comment by castamir** [comment]
Ok, I'll prepare PR to master, then.

But about renderer... isn't this exactly the reason why tests are written? If you change something, you should know, what is going to break. If you want to use some other way to test, then give me an example of a such test and I'll rewrite mine.

**Comment by dg** [comment]
When I change rendering of i.e. Checkbox, it should break test Controls.Checkbox.render.phpt, but not test written for ControlGroup. So `ControlGroup.phpt` is great and suffice.

**Comment by castamir** [comment]
Then how you plan to test ControlGroup rendering without controls? By adding ControlGroup rendering into tests like `Controls.Checkbox.render.phpt`? Hope not.

**Pull request closed without merging**
