### PR TITLE
ChoiceControl: trigger only user warning when default value is missing

### PR DESCRIPTION
**Pull request by Rixafy**
- BC break? yes, in some rare try-catch usages

It was annoying and probably most common error I've seen and it's a shame that whole page throws an error 500 instead of just not setting the default select value.

### CODE REVIEW

**Comment by dg** [comment]
It is better to kill a page with a 500 error than to cause an untraceable change to the database.

**Comment by Rixafy** [comment]
But this is just setting of default value that user sees when the form renders, page dies and form won't be rendered, it has nothing to do with submitting the form, values are chosen by an user anyway. Exception may be hidden field, but this change affects only choice controls (select boxes, radio boxes..) where the problem appears (because value can be out of allowed set by some mistake).

**Comment by Rixafy** [comment]
Argument could be made for some special forms that are submitted by some crawler bots or JS script, but by using choice control, programmers are purposely offering multiple select options and each value in that select box is valid and could be selected manually, so it's possible to change it.

It makes sense that if setting the default option fails, the option just won't be set as default and programmers will be notified. In the past years I had multiple errors that value is out of allowed set and firstly I thought it's a user warning that I'm trying to set non-existing value and I was surprised that it's a exception that kills whole app. In all the cases I have encountered, page would work correctly, just without some pre-selected value in the form.

**Comment by dg** [comment]
The exception indicates a serious bug because of which the form must not be submitted. You can turn off exception throwing. But the default behavior is entirely consistent with the spirit of Nette, which is to warn of serious errors and not allow the form to be submitted by default.

**Comment by dg** [comment]
Nette cannot distinguish what is an unimportant form for the user and what is an important form that must not be sent. The programmer has to distinguish that.

**Comment by Rixafy** [comment]
Ok, but it's not an invalid value, user can click the select and select custom value anyway, it's perfectly valid value and user sees it in the form, programmers will still get notified that user had wrong default value, but I'll get your point and for sure it's possible that there may be some JS forms that are submitted right after loading, or user is not used to change value of that form because he's expecting some value, but I still prefer to not to kill the whole page just because of that.

I can distinguish that, but even programmers make mistakes, especially when there is a lot of variability in list of items and default value, and in most cases I wouldn't mind, but I still want to get notified via at least warning, there are currently 2 options, one is to not check at all, another is to throw an exception. That' why I was pointing out I'll just use wrapper of choice inputs, since there is no option in between.

**Comment by dg** [comment]
What we are talking about here is a scenario where the user does _not_ click into the select box at all and submits the form. In that case, he _changed_ the value and nobody knows about it.

**Comment by Rixafy** [comment]
You are right, that will be a problem, I don't know why but I haven't thought about regular data editing at all in this use-case, because this error surprised me always somewhere else where I have more complex code to figure out default value.

**Pull request closed without merging**
