### PR TITLE
UploadControl: do not create NULL object (BC break!) [WIP]

### PR DESCRIPTION
**Pull request by dg**
This is big BC break and I don't know how to solve it in more gently way, so now it is only WIP.

Related to https://github.com/nette/http/pull/97

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Are you sure that `$this->getHttpData(Nette\Forms\Form::DATA_FILE)` can never return instance of `FileUpload` with `UPLOAD_ERR_NO_FILE`? Because I don't think that is the case.

**Comment by dg** [comment]
It can, of course. I think that reusing UPLOAD_ERR_NO_FILE, which is kind of upload error, for not-uploading-file was mistake.

**Comment by JanTvrdik** [comment]
I don't understand in what situations it will now return NULL. When `!isset($_FILES['myupload'])` (true for malicious requests only???)?
And in what situations it will now return instance with UPLOAD_ERR_NO_FILE. When the request is OK but user choose to not select file?

Am I complete wrong? I'm think I probably am but don't feel like doing my own research in how upload work 😄

**Comment by dg** [comment]
You're right!

**Pull request closed without merging**
