### PR TITLE
BaseControl: Return type of getControl() and getLabel() is never string.

### PR DESCRIPTION
**Pull request by janbarasek**
- bug fix
- BC break? yes

Fix for PhpStan level 6 where this generates an unrecoverable type error.

Rel https://github.com/nette/nette/pull/1418

### CODE REVIEW

**Comment by dg** [comment]
It can be string, why not?

**Comment by janbarasek** [comment]
For example, in this project code where `getControl()` is called, PhpStan throws an error and I always have to treat your method to return `Html`. I find this treatment unnecessary because the `Html` object will never be a string by implementation.

```php
/**
 * @param mixed|null $key
 * @return Html
 */
public function getControlPart($key = null): Html
{
   $key = key([(string) $key => null]);
   return parent::getControl()->addAttributes([
      'id' => $this->getHtmlId() . '-' . $key,
      'checked' => in_array($key, (array) $this->value, true),
      'disabled' => is_array($this->disabled) ? isset($this->disabled[$key]) : $this->disabled,
      'value' => $key,
   ]);
}
```

**Comment by dg** [comment]
But you can't solve that by limiting the return value and causing a huge BC break…

**Comment by janbarasek** [comment]
I honestly don't know the exact technical solution, but the truth is that the current bug makes it impossible to fix PhpStan tests to level 6 in application.

**Comment by dg** [comment]
Then just figure out the technical solution. And don't send a PR that'll break Nette.

**Pull request closed without merging**
