### PR TITLE
CheckboxList: Add same options as RadioList

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
By the way some tests are failing for me on windows (unrelated to this PR).

**Comment by matej21** [comment]
see #79

**Comment by enumag** [comment]
@matej21 That doesn't cover everything from this PR though.

**Comment by dg** [comment]
`RadioList::$generateId` exists only due to back compatiblity, it is not needed in CheckboxList.

**Comment by enumag** [comment]
@dg Ok, removed.

**Comment by enumag** [comment]
bump

**Pull request merged**
