### PR TITLE
SelectBox: Validation moved to rule

### LINKED ISSUE #3: SelectBox validation
Is there any reason why SelectBox don't use standart validation via addRule? Can I prepare pull-request that replace overriding of validate method with addRule?

There is problem that when I forgot to render some select, I can't get input label in error message - becouse placeholders are not replaced...

### PR DESCRIPTION
**Pull request by norbe**
Closes #3

### CODE REVIEW

**Comment by milo** [comment]
@norbe Could you move validation into closure? It will prevent adding `data-rule`.

**Comment by dg** [comment]
@milo this is not possible, because this PR is about error message matches with callback name…

**Comment by matej21** [comment]
@dg you can use sth like
```php
->addRule(function () { ..}, Nette\Forms\Validator::$messages[self::VALID])
```
or am I missing something?

**Comment by dg** [comment]
Jovlastně

**Comment by dg** [comment]
Merged 733a2e011ccce0bd992dbccf37758e838371ba0c

**Pull request closed without merging**
