### PR TITLE
added FormsExtension for Nette DI container

### PR DESCRIPTION
**Pull request by dg**
Updated  #49, see nette/bootstrap#4

### CODE REVIEW

**Comment by hrach** [comment]
Well, the conflict in all pull request can cause troubles. What if I have 2.2 DI, 2.3 forms and don't wanna use this Extension? (Also, almost everywhere will work the nette 2.2 extension.)

**Comment by JanTvrdik** [comment]
That you will simply be required to use nette/di 2.3. Is that so bad? I don't think there is a simple way around that.

**Comment by dg** [comment]
@hrach This is a situation that I have no idea how to solve.

**Comment by xificurk** [comment]
I don't think it's that big deal... You'll either need to stay with Forms 2.2 or update DI.
The conflict statement is needed, because allowing installation of incompatible packages is a big no-no.
Furthermore, you could say the same thing about any other class (in any other package) - I don't use class XYZ, therefore I don't need dependency abc/def, because everything else works without it.

**Comment by hrach** [comment]
It is a big deal. Classes in Bridges subnamespace are either dependency or doesn't have conflicts. Propper solution would be to put this to separate package, I understand it's seems useless, but this game with mixing up only some composer properties will lead to the hell.

There is an unwritten rule: **If some one uses classes from Bridges namespace, it's his task to provide propper dependencies.** Let's keep it or change it.

**Comment by hrach** [comment]
Also, you are forgeting about realworld. Requiring 2.2.x is not only my decission as a project developer, but it depends on decission of developers all my project dependencies. That's the reason why we are trying to make all dependencies the lowest, thah should be the most important feature of spliting nette - allowing to use different version of its components.

**Comment by dg** [comment]
I also do not like it.

**Comment by hrach** [comment]
What is the reason to put there the conflict? What are the benefits? The conflict should be in the nette/bootstrap, because it's his doing to register the extension automatically. Otherwise, it's user's responsibility to require proper dependencies.

**Comment by dg** [comment]
I don't know how to define version constrains for "other end of bridge". Even if it is user responsibility, it should be somehow defined.

**Comment by dg** [comment]
I have removed 'conflict di < 2.3', so far.

**Comment by hrach** [comment]
@dg Great! I really appreciate it.

**Pull request merged**
